server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    charset utf-8;

    gzip on;
    gzip_types text/plain text/css text/html application/javascript;

    location = / {
        try_files /index.html =404;
    }

    location = /politicas-privacidad {
        try_files /politicas-privacidad.html =404;
    }

    location = /privacy {
        return 302 /politicas-privacidad;
    }

    location = /privacy-policy {
        return 302 /politicas-privacidad;
    }

    location / {
        try_files $uri $uri.html =404;
    }
}
